### ISSUE TITLE
Self-hostable version via Docker

### ISSUE THREAD

**Issue by konklone** [konklone/fisacourt#10]
Use [Docker](http://www.docker.io/) to create a self-host-able container of this project. It can live in the Docker Index under my username (konklone/fisa).

I'm not really sure what this will entail yet. It could just be a Dockerfile in the root, or it could also mean some scripts and a crontab in a /deploy dir that manage what happens on a server.

Checking on health is the hardest part - if you want to check by asking the script, it needs to at least have an open port and a domain name associated, which is a lot of extra stuff to configure, and is host-specific and outside the scope of Docker (like interacting with AWS security groups, etc.). If you want to check the other way, by having a script run with a heartbeat, you need to have some central thing running to receive those checks (or use some service out in the world to receive them?).

Another problem is communicating configuration. How to update the docker container's configuration with things like Twilio credentials or SMTP details?

The end goal for this ticket is to have a set of developer-focused instructions that say what commands to run to start the code running, and how to auth their version of it with their own Twilio account or SMTP server.

Required for this ticket:
- [ ] Add crontab and any needed bash script helper for it to run
- [ ] Create Dockerfile that successfully installs dependencies, app, copies config.yml.example to config.yml, etc.
- [ ] Have crontab automatically enabled and running
- [ ] Build and publish this container to the Docker index
- [ ] Documentation for using it

Optional:
- [ ] Define command that turns on and turns off the watching (wiping or replacing crontab)
- [ ] Define test command that runs `fisa.rb test`
- [ ] Define command to see latest output

**Comment by konklone** [comment]
An FYI for anyone watching, I am continuing to chip away at this, have successfully fired off actual SMSes from within a Docker container, and just need to figure out the right cron solution (cron doesn't appear to function well within Docker).

**Comment by konklone** [comment]
Okay, this is working as of https://github.com/konklone/fisa/commit/d54f6d90064b4353d19a29e5c40fddcc9b8a1971. Instructions have been [added to the README](https://github.com/konklone/fisa#use-with-docker). 

It requires each user building the container themselves, since you need to edit your own `config.yml` file and then have the build script copy it into the container with your OAuth keys and the like.

@adelevie, my Docker muse, can I summon you to test out that my container, and README instructions, work for other people besides myself?

**Comment by adelevie** [comment]
Yes. Now go to bed :)
