### ISSUE TITLE
Moving to CC0

### ISSUE THREAD

**Issue by konklone** [konklone/fisacourt#14]
It's Unlicense now, but I didn't have a `CONTRIBUTING.md` before, so if you can, can I get a quick :+1: from @msjoinder, @compleatang and @benbalter? I'm adding one that explicitly says any contributions are entering the public domain.

**Comment by misjoinder** [comment]
Good by me :+1:

**Comment by benbalter** [comment]
:+1: :us:

**Comment by compleatang** [comment]
:thumbsup:

**Comment by konklone** [comment]
Thanks, all!
