### ISSUE TITLE
Maintain a public RSS feed

### ISSUE THREAD

**Issue by konklone** [konklone/fisacourt#4]
Not sure of the right integration strategy here - probably an `rss` field in `config.yml` where you put the path to an XML file you want it to write. Then, it's on the user to serve that XML file through a web server or whatever.

**Comment by konklone** [comment]
Now that I've moved `fisa.html` to be versioned in the `docket` branch, and for that to be the only activity on there, we have an effect Atom feed for FISA Court docket updates:

> [https://github.com/konklone/fisa/commits/docket.atom](https://github.com/konklone/fisa/commits/docket.atom)

Currently, that feed is full of commits that I made in the process of preparing the `docket` branch, but it should be exclusively `fisa.html` updates going forward. So, I'm considering this ticket resolved.

**Comment by compleatang** [comment]
Cool. Nice to see how the work is progressing here!
